// <auto-generated />
using System;
using CCCInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCCInventory.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260410041947_AddAuth")]
    partial class AddAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CCCInventory.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CCCInventory.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StaffMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CCCInventory.Cake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CakeFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CakeShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Flavor2")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LayerFlavors")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumTierLayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SplitTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TierSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Cakes");
                });

            modelBuilder.Entity("CCCInventory.Cookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookieQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CookieSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("CookieType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Cookies");
                });

            modelBuilder.Entity("CCCInventory.Cupcake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CupcakeFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CupcakeQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CupcakeSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Cupcakes");
                });

            modelBuilder.Entity("CCCInventory.OptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInUse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OptionItems");
                });

            modelBuilder.Entity("CCCInventory.Order", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancelledFlag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConfirmationTextSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContractSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOrderPlaced")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DayOfTextSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DepositAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DepositDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepositPaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalPaymentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalPaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FlavorUpgrade")
                        .HasColumnType("REAL");

                    b.Property<string>("InitialContact")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadyForPickup")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Labor")
                        .HasColumnType("REAL");

                    b.Property<double?>("LookbookPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("OrderDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PaidInFull")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalCost")
                        .HasColumnType("REAL");

                    b.HasKey("OrderNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CCCInventory.OrderAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrderAttachments");
                });

            modelBuilder.Entity("CCCInventory.OtherItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("OtherItems");
                });

            modelBuilder.Entity("CCCInventory.Pupcake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PupcakeQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PupcakeSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Pupcakes");
                });

            modelBuilder.Entity("CCCInventory.SignatureCupcake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CupcakeFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SignatureCupcakes");
                });

            modelBuilder.Entity("CCCInventory.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("CCCInventory.AuditLog", b =>
                {
                    b.HasOne("CCCInventory.StaffMember", "StaffMember")
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("CCCInventory.Cake", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("Cakes")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.Cookie", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("Cookies")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.Cupcake", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("Cupcakes")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.OtherItem", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("OtherItems")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.Pupcake", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("Pupcakes")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.Order", b =>
                {
                    b.Navigation("Cakes");

                    b.Navigation("Cookies");

                    b.Navigation("Cupcakes");

                    b.Navigation("OtherItems");

                    b.Navigation("Pupcakes");
                });
#pragma warning restore 612, 618
        }
    }
}
