// <auto-generated />
using System;
using CCCInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCCInventory.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260221221033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CCCInventory.Cake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CakeFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CakeShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumTierLayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SplitTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TierSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Cakes");
                });

            modelBuilder.Entity("CCCInventory.Cookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookieQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CookieType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Cookies");
                });

            modelBuilder.Entity("CCCInventory.Cupcake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CupcakeFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CupcakeQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CupcakeSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FillingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IcingFlavor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Cupcakes");
                });

            modelBuilder.Entity("CCCInventory.Order", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConfirmationTextSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContractSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOrderPlaced")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DayOfTextSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DepositAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DepositDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepositPaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalPaymentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalPaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialContact")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrderDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PaidInFull")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("PickupOrDelivery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryPhone")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalCost")
                        .HasColumnType("REAL");

                    b.HasKey("OrderNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CCCInventory.OrderAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrderAttachments");
                });

            modelBuilder.Entity("CCCInventory.Pupcake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PupcakeQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PupcakeSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Pupcakes");
                });

            modelBuilder.Entity("CCCInventory.Cake", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("Cakes")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.Cookie", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("Cookies")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.Cupcake", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("Cupcakes")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.Pupcake", b =>
                {
                    b.HasOne("CCCInventory.Order", null)
                        .WithMany("Pupcakes")
                        .HasForeignKey("OrderNumber");
                });

            modelBuilder.Entity("CCCInventory.Order", b =>
                {
                    b.Navigation("Cakes");

                    b.Navigation("Cookies");

                    b.Navigation("Cupcakes");

                    b.Navigation("Pupcakes");
                });
#pragma warning restore 612, 618
        }
    }
}
