import { Cake } from "./cake";
import { Cookie } from "./cookie";
import { Cupcake } from "./cupcake";
import { OtherItem } from "./other-item";
import { Pupcake } from "./pupcake";

export class Order {
  orderNumber: number | undefined;
  orderDateTime: Date | undefined;
  deliveryLocation?: string;
  custName: string | undefined;
  custEmail?: string | undefined;
  custPhone: string | undefined;
  details: string | undefined;
  orderType?: string;
  secondaryName?: string;
  secondaryPhone?: string;
  initialContact?: string;
  contractSent?: boolean | false;
  dayOfTextSent?: boolean | false;
  confirmationTextSent?: boolean | false;
  cakes?: Array<Cake>;
  cupcakes?: Array<Cupcake>;
  pupcakes?: Array<Pupcake>;
  cookies?: Array<Cookie>;
  otherItems?: Array<OtherItem>;
  totalCost?: number;
  depositAmount?: number;
  depositPaymentMethod?: string;
  depositDateTime?: Date;
  finalPaymentMethod?: string;
  finalPaymentDateTime?: Date;
  dateOrderPlaced: Date | undefined;
  paidInFull?: boolean | undefined;
  cancelledFlag?: boolean | false;
  title?: string;
  cancellationReason?: string;
  cancelledAt?: Date;
  isReadyForPickup?: boolean;
  labor?: number;
  flavorUpgrade?: number;
  lookbookPrice?: number;
}
